os: osx
language: python
python:
- '3.8'
deploy:
  provider: heroku
  app: pollakpoker
  on:
    repo: tom-pollak/web_poker
  api_key:
    secure: u/jfSWaAJ0GHQv++jxfTLrjc5xm3dRucsHvtx0/lfh5ARxldX/kwifUUoy0gTfd4Qz4XMf4P3rbJ1ifpKmQOdSLx1PEclY4SrAUKEV5Yg8pWPTk6g4L4BJxuFZ7+DfizxySj4+VvMO9MKPib4JDG28MzOLJjwZ83Sc6ecKRQdjJEVA8wW21oaJj/LAVT47+rQYTjn110LFzzp1iej7gR0omMjRSOGwFVd6B4ioLfhD+nSmGVz/tjoEfdU6XSjsmccyG0z/RrqgNRxVpHxMW8wtC3kPpslTOVsJWsLpk2iqlVgvCF9vPZrVAzn9H/74bKsC1fQgL1akhuSVEmtSBM5NR11awVhG2fyKJDQZbnWfHQVKQnFxjC04Td/D1FSqzVx5s/I+TJIdWmcCDmaT+mfwls570qE341vSXb3b6IYLngZbsOo5B37ld+azIBtxLFPC0Jbr+NeOinvYiQ0aQR0J+MKN2okd8mzK1n8Ve9qDi8j2y/owcybps9eWj1/Ggw5MVSL3dOsBow0fovt4CYIwDqsc8WI09C0Lp9FXMAm1wZj8ZLjVmHF6iVF9XULRfycFV/00oU/3YGVkun3ltibODMHVScWhNF6MGOVULDgC7gKt3pmkhwhvHFSZqOyi88R0VfwOjSC+Ga5t7Ww9fmxmEX57uraRQulymS7ovnhbs=
