version: "3.8"
services:
    web:
        build: .
        # command: python manage.py cleartables
        command: daphne project.asgi:application --port 8000 --bind 0.0.0.0 -v2
        # command: python manage.py runserver 0.0.0.0:8000
        # command: gunicorn project.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - target: 8000
              published: $PORT

        #depends_on:
        #- db
        #- redis_db

    redis_db:
        image: "redis:5"
        ports:
            - "6379:6379"

    db:
        image: "postgres:12-alpine"
        ports:
            - "5432"

        environment:
            - POSTGRES_DB=db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
